name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm build
        env:
          SC_KEY_A1: ${{ secrets.SC_KEY_A1 }}
          SC_SECRET_A1: ${{ secrets.SC_SECRET_A1 }}
      - name: Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_USESECANT }}
          channelId: live
          projectId: usesecant
      - name: Monoserve
        uses: KTibow/monoserve/deploy@main
        with:
          config-broker-url: "https://config-broker.ktibow.workers.dev"
